//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gov.uscourts.ao.rest.dal.Domain
{
    using gov.uscourts.ao.rest.dal.Interfaces.IDomain;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ClientAssign //: IClientAssign
    {
        [Key]
        public int AssignNum { get; set; }
        public string CCID { get; set; }
        public string CSID { get; set; }
        public string DisplayName { get; set; }
        public string StaffName { get; set; }
        public string PactsType { get; set; }
        public Nullable<int> QuestionSetID { get; set; }
        public string office_location { get; set; }
        public string Schedule { get; set; }
        public string Venue { get; set; }
        public Nullable<bool> Active { get; set; }
        public System.DateTime DateRegistered { get; set; }
        public string RegisteredBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Enrolled { get; set; }
        public Nullable<System.DateTime> DateEnrolled { get; set; }
        public string EnrolledBy { get; set; }
        public Nullable<System.DateTime> DateDeactivated { get; set; }
        public string DeactivatedBy { get; set; }
        public Nullable<bool> PACTS_Closed { get; set; }
        public Nullable<int> ScheduleID { get; set; }
    }
}
